name: Cross Build aarch64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cross-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build cross image
        run: |
          cd node
          docker build -t my-rust-cross-aarch64 .

      - name: Install cross
        run: cargo install cross

      - name: Cross build
        run: |
          cd node
          cross build --release --target aarch64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: edgenode-aarch64
          path: node/target/aarch64-unknown-linux-gnu/release/edgenode
          if-no-files-found: error
