name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './master'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build Inventory Image'
        run: |
          docker build . \
            --tag ghcr.io/smartlinuxcoder/edgenode-master:latest
          docker push ghcr.io/smartlinuxcoder/edgenode-master:latest

      - name: 'Deploy to Coolify'
        run: |
          curl -X POST "https://coolify.smart.is-a.dev/api/v1/deploy?uuid=hs80cwg4kso80s8ocggsk48c&force=false" \
          -H "Authorization: Bearer${{ secrets.COOLIFY_TOKEN }}"